// Curated Indian domestic airports (IATA -> city, state). Origin BLR is excluded
// from the picker since it's locked. A *state* can have several airports, so the
// search box matches on city AND state (typing "Kerala" surfaces COK/TRV/CCJ).
window.AIRPORTS = [
  { iata: "DEL", city: "Delhi",              state: "Delhi" },
  { iata: "BOM", city: "Mumbai",             state: "Maharashtra" },
  { iata: "MAA", city: "Chennai",            state: "Tamil Nadu" },
  { iata: "CCU", city: "Kolkata",            state: "West Bengal" },
  { iata: "HYD", city: "Hyderabad",          state: "Telangana" },
  { iata: "COK", city: "Kochi",              state: "Kerala" },
  { iata: "TRV", city: "Thiruvananthapuram", state: "Kerala" },
  { iata: "CCJ", city: "Kozhikode",          state: "Kerala" },
  { iata: "GOI", city: "Goa (Dabolim)",      state: "Goa" },
  { iata: "GOX", city: "Goa (Mopa)",         state: "Goa" },
  { iata: "PNQ", city: "Pune",               state: "Maharashtra" },
  { iata: "NAG", city: "Nagpur",             state: "Maharashtra" },
  { iata: "IXU", city: "Aurangabad",         state: "Maharashtra" },
  { iata: "AMD", city: "Ahmedabad",          state: "Gujarat" },
  { iata: "STV", city: "Surat",              state: "Gujarat" },
  { iata: "BDQ", city: "Vadodara",           state: "Gujarat" },
  { iata: "RAJ", city: "Rajkot",             state: "Gujarat" },
  { iata: "JAI", city: "Jaipur",             state: "Rajasthan" },
  { iata: "UDR", city: "Udaipur",            state: "Rajasthan" },
  { iata: "JDH", city: "Jodhpur",            state: "Rajasthan" },
  { iata: "LKO", city: "Lucknow",            state: "Uttar Pradesh" },
  { iata: "VNS", city: "Varanasi",           state: "Uttar Pradesh" },
  { iata: "PAT", city: "Patna",              state: "Bihar" },
  { iata: "BBI", city: "Bhubaneswar",        state: "Odisha" },
  { iata: "IXR", city: "Ranchi",             state: "Jharkhand" },
  { iata: "RPR", city: "Raipur",             state: "Chhattisgarh" },
  { iata: "IDR", city: "Indore",             state: "Madhya Pradesh" },
  { iata: "BHO", city: "Bhopal",             state: "Madhya Pradesh" },
  { iata: "JLR", city: "Jabalpur",           state: "Madhya Pradesh" },
  { iata: "VTZ", city: "Visakhapatnam",      state: "Andhra Pradesh" },
  { iata: "VGA", city: "Vijayawada",         state: "Andhra Pradesh" },
  { iata: "TIR", city: "Tirupati",           state: "Andhra Pradesh" },
  { iata: "CJB", city: "Coimbatore",         state: "Tamil Nadu" },
  { iata: "IXM", city: "Madurai",            state: "Tamil Nadu" },
  { iata: "TRZ", city: "Tiruchirappalli",    state: "Tamil Nadu" },
  { iata: "IXE", city: "Mangaluru",          state: "Karnataka" },
  { iata: "HBX", city: "Hubballi",           state: "Karnataka" },
  { iata: "IXC", city: "Chandigarh",         state: "Chandigarh" },
  { iata: "ATQ", city: "Amritsar",           state: "Punjab" },
  { iata: "DED", city: "Dehradun",           state: "Uttarakhand" },
  { iata: "IXJ", city: "Jammu",              state: "Jammu & Kashmir" },
  { iata: "SXR", city: "Srinagar",           state: "Jammu & Kashmir" },
  { iata: "IXL", city: "Leh",                state: "Ladakh" },
  { iata: "GAU", city: "Guwahati",           state: "Assam" },
  { iata: "DIB", city: "Dibrugarh",          state: "Assam" },
  { iata: "IXS", city: "Silchar",            state: "Assam" },
  { iata: "IXB", city: "Bagdogra",           state: "West Bengal" },
  { iata: "IXA", city: "Agartala",           state: "Tripura" },
  { iata: "IMF", city: "Imphal",             state: "Manipur" },
  { iata: "DMU", city: "Dimapur",            state: "Nagaland" },
  { iata: "SHL", city: "Shillong",           state: "Meghalaya" },
  { iata: "PNY", city: "Puducherry",         state: "Puducherry" },
  { iata: "IXZ", city: "Port Blair",         state: "Andaman & Nicobar" },
];
